version: '3.8'

services:
  webhook-bot:
    image: ghcr.io/dignezzz/webhook_tg_bot:latest
    container_name: webhook_tg_bot_prod
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    environment:
      - WEBHOOK_PORT=8080
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
